name: Feature Branch Workflow

on:
  push:
    branches: [ feature/* ]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          NESTJS_APP: true
      - name: Build
        run: devops/scripts/build.sh
      - name: Run Unit Tests
        run: devops/scripts/unit-tests.sh
      - name: Testing Variables
        run: |
          OUTPUT=$(date);
          echo "::set-output name=OUTPUT::$OUTPUT"
        id: output
      - name: Output Variables
        run: echo "Date Captured = ${{ steps.output.outputs.OUTPUT  }}"
      - name: Set Env Value
        run: echo "my_name=regeti" >> $GITHUB_ENV

  DevelopmentDeployment:
    needs: Build-Test
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://DEVELOPMENT.deployment.org'
    steps:
      - name: Deployment
        if:   github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "Include steps to deploy to Development Environment"

  TestDeployment:
    needs: DevelopmentDeployment
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: 'http://TEST.deployment.org'
    steps:
      - name: Deployment
        run: |
          echo "Include steps to deploy to Test Environment"
          echo ${{ env.my_name  }}

        
  StageDeployment:
    needs: TestDeployment
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://STAGE.deployment.org'
    steps:
      - name: Deployment
        run: echo "Include steps to deploy to Test Environment"
