name: Feature Branch Workflow

on:
  push:
    branches: [ feature/* ]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          NESTJS_APP: true
      - name: Build
        run: devops/scripts/build.sh
      - name: Run Unit Tests
        run: devops/scripts/unit-tests.sh

  DevelopmentDeployment:
    needs: Build-Test
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://development.deployment.org'
    steps:
      - name: Deployment
        run: echo "Include steps to deploy to Development Environment"

  TestDeployment:
    needs: DevelopmentDeployment
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: 'http://test.deployment.org'
    steps:
      - name: Deployment
        run: echo "Include steps to deploy to Test Environment"

        
  StageDeployment:
    needs: TestDeployment
    runs-on: ubuntu-latest
    environment:
      name: Stage
      url: 'http://stage.deployment.org'
    steps:
      - name: Deployment
        run: echo "Include steps to deploy to Test Environment"
