# The following are valid TAG formats (tst-1.0.101, stg-1.0.101, rbk-1.0.101)
name: Staging Deployment Workflow

on:
  push:
    branches: [ release/v* ]
    tags:
      - stg-[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ release/v* ]
    tags:
      - stg-[0-9]+.[0-9]+.[0-9]+

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV: stg
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_STG_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_STG_DEPLOYMENT_SVC_PWD }}
      - name: Get Tag
        # may move to bash script!!!
        run: echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
        # this has been depricated --> echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - name: Deploy
        run: devops/scripts/deploy.sh
        env:
          DEPLOY_FROM_ARTIFACT: true
