# The following are valid TAG formats (tst-1.0.101, stg-1.0.101, rbk-1.0.101)
name: Staging Deployment Workflow

on:
  push:
    branches: [ release/v* ]
    tags:
      - stg-[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ release/v* ]
    tags:
      - stg-[0-9]+.[0-9]+.[0-9]+

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Check Tag
        run: devops/scripts/check-tag.sh
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_STG_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_STG_DEPLOYMENT_SVC_PWD }}
      - name: Deploy
        run: devops/scripts/deploy.sh
        env:
          DEPLOY_FROM_ARTIFACT: true
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
